// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using meal_plan_generator.Context;

#nullable disable

namespace meal_plan_generator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230107080308_nutrients")]
    partial class nutrients
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("meal_plan_generator.Models.MealPlan.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CaloriesPerServing")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ServingSize")
                        .HasColumnType("float");

                    b.Property<double>("Servings")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("meal_plan_generator.Models.MealPlan.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("meal_plan_generator.Models.MealPlan.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("meal_plan_generator.Models.MealPlan.Nutrient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<int?>("FoodId")
                        .HasColumnType("int");

                    b.Property<int?>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NutrientSettingsId")
                        .HasColumnType("int");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("FormId");

                    b.HasIndex("NutrientSettingsId");

                    b.ToTable("Nutrient");
                });

            modelBuilder.Entity("meal_plan_generator.Models.MealPlan.NutrientSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("IdealAmount")
                        .HasColumnType("real");

                    b.Property<int>("Intercept")
                        .HasColumnType("int");

                    b.Property<float>("LowerBound")
                        .HasColumnType("real");

                    b.Property<int>("NutrientId")
                        .HasColumnType("int");

                    b.Property<float>("UpperBound")
                        .HasColumnType("real");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NutrientSettings");
                });

            modelBuilder.Entity("meal_plan_generator.Models.MealPlan.Nutrient", b =>
                {
                    b.HasOne("meal_plan_generator.Models.MealPlan.Food", null)
                        .WithMany("Nutrients")
                        .HasForeignKey("FoodId");

                    b.HasOne("meal_plan_generator.Models.MealPlan.Form", null)
                        .WithMany("NutrientData")
                        .HasForeignKey("FormId");

                    b.HasOne("meal_plan_generator.Models.MealPlan.NutrientSettings", "Settings")
                        .WithMany()
                        .HasForeignKey("NutrientSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("meal_plan_generator.Models.MealPlan.Food", b =>
                {
                    b.Navigation("Nutrients");
                });

            modelBuilder.Entity("meal_plan_generator.Models.MealPlan.Form", b =>
                {
                    b.Navigation("NutrientData");
                });
#pragma warning restore 612, 618
        }
    }
}
